const mainCity = document.getElementById("city");
const time = document.getElementById("time");
const mainTemp = document.getElementById("temp");
const feelsLike = document.getElementById("feelsLike");
const conditions = document.getElementById("conditions");
const dayForecast = document.getElementById("dayForecast");
const wind = document.getElementById("wind");
const precipit = document.getElementById("precipit");
const icon = document.getElementById("icon");
const daysDiv = document.getElementById('daysDiv');
const loading = document.getElementById("loading");
const errorMessage = document.getElementById("errorMessage");
const mainPanel = document.getElementById("mainPanel");

import { formatDate, formatTime } from "./utilities";

export function errorDisplay(message) {

// selector for items to clear if error
const mainTextElements = mainPanel.querySelectorAll(
    "#city, #time, #temp, #conditions, #feelsLike, #precipit, #wind, #dayForecast"
);

icon.textContent = "";
daysDiv.textContent = "";

mainTextElements.forEach(element => {
    element.textContent = "";
});

errorMessage.textContent = message;

}

//Main Panel Render
export async function displayMain (weatherInfo) {

errorMessage.textContent = "";
const city = weatherInfo.city
const cityCap = city.toUpperCase();
mainCity.textContent = cityCap;

time.textContent = `Time: ${formatTime(weatherInfo.time)}`;

mainTemp.textContent = `Max: ${weatherInfo.tempmax}° Min: ${weatherInfo.tempmin}°`;

conditions.textContent = `${weatherInfo.current}`;

//dynamic icons import
const iconModule = await import(`./images/${weatherInfo.icon}.svg`);
icon.textContent = "";
const img = document.createElement("img");
img.classList.add("main-weather-icon")
//the value generated by Webpack for the asset
img.src = iconModule.default;
icon.appendChild(img);

feelsLike.textContent = `Feels like: ${weatherInfo.feelsLike}°`;

precipit.textContent = `Rain: ${weatherInfo.precipProb}%`;
wind.textContent = `Wind: ${weatherInfo.wind}`;

dayForecast.textContent = `Later: ${weatherInfo.dayForecast}`;


};

//7 days forecast
export async function displayWeek(forecast){

daysDiv.textContent = "";

const week = forecast.slice(1,8);


// for allows for async, forEach doesn't
for (const item of week) {

const card = document.createElement('div');
card.classList.add("forecast-card");

const day = document.createElement("div");

const iconModule = await import(`./images/${item.icon}.svg`);
const img = document.createElement("img");
img.classList.add("weather-icon");
img.src = iconModule.default;

const temperatures = document.createElement("div");
const conditions = document.createElement("div");
const precipitation = document.createElement("div");

day.textContent = `${formatDate(item.datetime)}`;
temperatures.textContent = `${item.tempmax}° / ${item.tempmin}°`;
conditions.textContent = item.conditions;
precipitation.textContent = `Rain ${item.precipprob}%`;


daysDiv.appendChild(card)
card.appendChild(day);
card.appendChild(img);
card.appendChild(temperatures);
card.appendChild(conditions);
card.appendChild(precipitation)


}
 
}

export function showLoading (cityName) {
    loading.textContent= `Loading ${cityName}...`;
}

export function hideLoading () {
    loading.textContent = "";
}